/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmsc_335_project_2_september_9;

import java.util.HashMap;
import java.util.Map;

import javafx.application.Application;
import javafx.scene.Node;
import javafx.scene.control.ComboBox;
import javafx.scene.image.ImageView;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import utils.ConstantValues;
import utils.LayoutFactory;
import utils.ShapeFactory;

public class App extends Application {

    private Stage primaryStage = new Stage();
    Map<String, Node> currentDrawingImageMap = new HashMap<>(
            Map.of(
                    ConstantValues.SHAPE_KEY, new Rectangle(),
                    ConstantValues.IMAGE_KEY, new ImageView()));

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        primaryStage = stage;
        primaryStage.setTitle("Shape Drawing App");

        ComboBox<ShapeFactory> shapeComboBox = new ComboBox<>();
        shapeComboBox.getItems().addAll(ShapeFactory.values());
        shapeComboBox.setOnAction(
                event -> LayoutFactory.createStage(primaryStage, shapeComboBox.getValue(), shapeComboBox,
                        currentDrawingImageMap));

        LayoutFactory.createStage(primaryStage, ShapeFactory.values()[0], shapeComboBox, currentDrawingImageMap);
    }

}
