/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmsc_335_project_2_september_9;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    // App classUnderTest = new App();
    // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
